import {
	StyleSheet, Font,
} from '@react-pdf/renderer';

// Register TeleNeo Font Family
Font.register({
	family: 'TeleNeo',
	fonts: [
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-Regular.otf',
			fontWeight: 'normal',
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-RegularItalic.otf',
			fontStyle: 'italic',
			fontWeight: 'normal',
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-Medium.otf',
			fontWeight: 'medium',
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-MediumItalic.otf',
			fontStyle: 'italic',
			fontWeight: 'medium',
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-Bold.otf',
			fontWeight: 'bold',
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-BoldItalic.otf',
			fontStyle: 'italic',
			fontWeight: 'bold',
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-Thin.otf',
			fontWeight: 100,
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-ThinItalic.otf',
			fontStyle: 'italic',
			fontWeight: 100,
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-ExtraBold.otf',
			fontWeight: 800,
		},
		{
			src: '/fonts/TeleNeo/desktop_otf/TeleNeo-Ultra.otf',
			fontWeight: 900,
		},
	],
});

export const COLORS = {
	magenta: '#e20074',
	dark: '#191919',
	gray: '#6a6a6a',
	lightGray: '#f2f2f2',
	white: '#ffffff',
	blueBorder: '#0076b4',
	softBlueBg: '#f4f8fb',
	lightBlueBorder: '#b3d4ec',
	pinkBadgeBg: '#fff0f6',
	lightPinkBg: '#fffbfd',
};

export const styles = StyleSheet.create({
	page: {
		paddingTop: 40,
		paddingBottom: 50,
		paddingHorizontal: 40,
		backgroundColor: COLORS.white,
		fontFamily: 'TeleNeo',
		fontSize: 9,
		lineHeight: 1.4,
		color: COLORS.dark,
	},
	headerContainer: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		marginBottom: 20,
	},
	logoContainer: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	logoSvgPlaceholder: {
		backgroundColor: COLORS.magenta,
		paddingVertical: 10,
		paddingHorizontal: 15,
		borderRadius: 8,
	},
	logoTextLarge: {
		color: COLORS.white,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 16,
		letterSpacing: -0.5,
	},
	logoTextSmall: {
		color: COLORS.white,
		fontSize: 8,
		marginTop: 2,
	},
	dateText: {
		color: COLORS.dark,
		fontSize: 8,
		textAlign: 'right',
		marginTop: 5,
	},
	pageTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 18,
		color: COLORS.dark,
		marginBottom: 15,
	},
	sectionTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 14,
		color: COLORS.magenta,
		marginTop: 15,
		marginBottom: 8,
	},
	sectionHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		borderBottomWidth: 1,
		borderBottomColor: COLORS.lightGray,
		paddingBottom: 4,
		marginBottom: 10,
	},
	sectionHeaderTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 10,
		color: COLORS.dark,
	},
	sectionHeaderColumns: {
		flexDirection: 'row',
		width: 180,
		justifyContent: 'space-between',
	},
	sectionHeaderColText: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 8,
		color: COLORS.dark,
		textAlign: 'right',
		width: 70,
	},
	sectionHeaderColMonthly: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 8,
		color: COLORS.dark,
		textAlign: 'right',
		width: 110,
	},
	sectionHeaderColOneTime: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 8,
		color: COLORS.dark,
		textAlign: 'right',
		width: 70,
	},
	productCard: {
		borderWidth: 1,
		borderColor: COLORS.lightBlueBorder,
		borderRadius: 6,
		padding: 12,
		marginBottom: 10,
		backgroundColor: COLORS.white,
	},
	productCardHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		marginBottom: 6,
	},
	productName: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 11,
		color: COLORS.dark,
		flex: 1,
		marginRight: 10,
	},
	priceArea: {
		flexDirection: 'row',
		width: 180,
		justifyContent: 'space-between',
		alignItems: 'flex-start',
	},
	monthlyPriceCol: {
		width: 110,
		alignItems: 'flex-end',
	},
	oneTimePriceCol: {
		width: 70,
		alignItems: 'flex-end',
	},
	priceText: {
		fontSize: 11,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.magenta,
	},
	oneTimePriceText: {
		fontSize: 11,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.dark,
	},
	crossedOutPrice: {
		fontSize: 8,
		color: COLORS.gray,
		textDecoration: 'line-through',
		marginBottom: 2,
	},
	priceSubNote: {
		fontSize: 7,
		color: COLORS.gray,
		textAlign: 'right',
		marginTop: 2,
	},
	contractDuration: {
		fontSize: 8,
		color: COLORS.gray,
		marginBottom: 8,
	},
	bulletList: {
		marginTop: 4,
		marginBottom: 8,
	},
	bulletItem: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		marginBottom: 3,
		paddingLeft: 5,
	},
	bulletDot: {
		width: 3,
		height: 3,
		borderRadius: 1.5,
		backgroundColor: COLORS.dark,
		marginTop: 4,
		marginRight: 6,
	},
	bulletText: {
		fontSize: 8,
		color: COLORS.dark,
		flex: 1,
		lineHeight: 1.3,
	},
	bulletTextBold: {
		fontSize: 8,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.dark,
		flex: 1,
		lineHeight: 1.3,
	},
	paragraphText: {
		fontSize: 8,
		color: COLORS.dark,
		lineHeight: 1.3,
	},
	paragraphTextBold: {
		fontSize: 8,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.dark,
		lineHeight: 1.3,
	},
	subSectionTitle: {
		fontSize: 8,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.dark,
		marginTop: 6,
		marginBottom: 4,
	},
	badgeRow: {
		flexDirection: 'row',
		alignItems: 'center',
		flexWrap: 'wrap',
		marginTop: 2,
	},
	badge: {
		backgroundColor: COLORS.magenta,
		borderRadius: 8,
		paddingHorizontal: 6,
		paddingTop: 1.5,
		paddingBottom: 2.5,
		marginLeft: 6,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	badgeText: {
		color: COLORS.white,
		fontSize: 6,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		textAlign: 'center',
		lineHeight: 1.0,
	},
	plusKarteUnlimitedContainer: {
		borderTopWidth: 1,
		borderTopColor: COLORS.lightGray,
		marginTop: 8,
		paddingTop: 8,
	},
	plusKarteHeartIcon: {
		color: COLORS.magenta,
		fontSize: 9,
		marginHorizontal: 3,
	},
	zusatzkartenHeader: {
		fontSize: 9,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.gray,
		textTransform: 'uppercase',
		marginBottom: 6,
		marginTop: 10,
	},
	zusatzkartenCard: {
		borderWidth: 1,
		borderColor: COLORS.lightBlueBorder,
		borderRadius: 6,
		padding: 10,
		marginBottom: 6,
		backgroundColor: COLORS.white,
	},
	zusatzkarteRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	zusatzkarteName: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 9,
		color: COLORS.dark,
	},
	zusatzkarteSubtext: {
		fontSize: 8,
		color: COLORS.gray,
		marginTop: 3,
	},
	teilsummeRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		backgroundColor: COLORS.softBlueBg,
		borderRadius: 6,
		paddingVertical: 10,
		paddingHorizontal: 12,
		marginTop: 12,
		marginBottom: 8,
	},
	teilsummeText: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 9,
		color: '#005b8f',
	},
	teilsummePrices: {
		flexDirection: 'row',
		width: 180,
		justifyContent: 'space-between',
	},
	teilsummeMonthlyText: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 10,
		color: COLORS.magenta,
		textAlign: 'right',
		width: 110,
	},
	teilsummeOneTimeText: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 10,
		color: COLORS.magenta,
		textAlign: 'right',
		width: 70,
	},
	rechnerischerBanner: {
		backgroundColor: COLORS.softBlueBg,
		borderRadius: 6,
		padding: 12,
		marginBottom: 15,
	},
	rechnerischerTitle: {
		fontSize: 9,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.dark,
		marginBottom: 4,
		lineHeight: 1.3,
	},
	rechnerischerPriceHighlight: {
		color: COLORS.magenta,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
	},
	rechnerischerDesc: {
		fontSize: 7,
		color: COLORS.gray,
		lineHeight: 1.3,
	},
	gesamtsummeContainer: {
		borderWidth: 2,
		borderColor: COLORS.magenta,
		borderRadius: 8,
		padding: 15,
		marginTop: 15,
		marginBottom: 15,
		backgroundColor: COLORS.lightPinkBg,
	},
	gesamtsummeHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		marginBottom: 10,
	},
	gesamtsummeTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 12,
		color: COLORS.magenta,
	},
	gesamtsummePrices: {
		flexDirection: 'row',
		width: 180,
		justifyContent: 'space-between',
	},
	gesamtsummeMonthlyText: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 13,
		color: COLORS.magenta,
		textAlign: 'right',
		width: 110,
	},
	gesamtsummeOneTimeText: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 13,
		color: COLORS.magenta,
		textAlign: 'right',
		width: 70,
	},
	gesamtsummeSteps: {
		alignItems: 'flex-end',
		borderTopWidth: 1,
		borderTopColor: COLORS.lightGray,
		paddingTop: 8,
		marginTop: 8,
	},
	gesamtsummeStepText: {
		fontSize: 8,
		color: COLORS.gray,
		marginBottom: 2,
	},
	gesamtsummeSavingsText: {
		fontSize: 9,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: '#00a878',
		marginTop: 4,
	},
	durchschnittSimBanner: {
		backgroundColor: COLORS.softBlueBg,
		borderRadius: 6,
		padding: 12,
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 15,
	},
	durchschnittSimText: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 9,
		color: COLORS.dark,
		textTransform: 'uppercase',
	},
	durchschnittSimPrice: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 11,
		color: COLORS.dark,
	},
	marketingBannersRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginBottom: 15,
		marginTop: 10,
	},
	marketingBanner: {
		width: '48%',
		borderRadius: 6,
		padding: 12,
		height: 115,
		justifyContent: 'space-between',
	},
	bannerTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 10,
		color: COLORS.white,
	},
	bannerSub: {
		fontSize: 7,
		color: COLORS.white,
		opacity: 0.9,
	},
	bannerFooter: {
		fontSize: 6,
		color: COLORS.white,
		opacity: 0.8,
	},
	legalNoticeBox: {
		backgroundColor: COLORS.softBlueBg,
		borderRadius: 6,
		padding: 10,
		marginTop: 10,
	},
	legalNoticeTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 8,
		color: COLORS.dark,
		marginBottom: 4,
	},
	legalNoticeText: {
		fontSize: 6.5,
		color: COLORS.gray,
		lineHeight: 1.3,
	},
	footerText: {
		fontSize: 7,
		color: COLORS.gray,
		textAlign: 'center',
		position: 'absolute',
		bottom: 25,
		left: 0,
		right: 0,
	},
	detailGrid: {
		marginTop: 10,
	},
	detailSection: {
		borderBottomWidth: 1,
		borderBottomColor: COLORS.lightGray,
		paddingBottom: 10,
		marginBottom: 10,
	},
	detailSectionTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 10,
		color: COLORS.dark,
		marginBottom: 6,
	},
	detailRow: {
		flexDirection: 'row',
		marginBottom: 4,
	},
	detailLabel: {
		width: 150,
		fontSize: 8,
		color: COLORS.gray,
	},
	detailValue: {
		flex: 1,
		fontSize: 8,
		color: COLORS.dark,
	},
	magentaEinsContainer: {
		borderWidth: 1.5,
		borderColor: COLORS.magenta,
		backgroundColor: COLORS.lightPinkBg,
		borderRadius: 6,
		padding: 12,
		marginBottom: 15,
	},
	magentaEinsHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 8,
		borderBottomWidth: 1,
		borderBottomColor: '#fbcde2',
		paddingBottom: 4,
	},
	magentaEinsTitle: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 10,
		color: COLORS.magenta,
	},
	magentaEinsBadge: {
		backgroundColor: COLORS.magenta,
		borderRadius: 8,
		paddingHorizontal: 6,
		paddingTop: 1.5,
		paddingBottom: 2.5,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	magentaEinsBadgeText: {
		color: COLORS.white,
		fontSize: 6,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		textAlign: 'center',
		lineHeight: 1.0,
	},
	magentaEinsSubTitle: {
		fontSize: 8,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.magenta,
		marginTop: 4,
		marginBottom: 2,
	},
	welcomeContainer: {
		backgroundColor: COLORS.softBlueBg,
		borderRadius: 6,
		padding: 12,
		marginBottom: 15,
	},
	welcomeText: {
		fontSize: 8,
		color: COLORS.dark,
		lineHeight: 1.4,
	},
	contactRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginTop: 10,
		marginBottom: 15,
	},
	contactCard: {
		width: '48%',
		borderWidth: 1,
		borderColor: COLORS.lightBlueBorder,
		borderRadius: 6,
		padding: 12,
		backgroundColor: COLORS.white,
	},
	contactCardProminent: {
		width: '48%',
		borderWidth: 1,
		borderColor: COLORS.magenta,
		borderRadius: 6,
		padding: 12,
		backgroundColor: COLORS.lightPinkBg,
	},
	contactCardSingle: {
		width: '100%',
		borderWidth: 1,
		borderColor: COLORS.lightBlueBorder,
		borderRadius: 6,
		padding: 12,
		backgroundColor: COLORS.white,
	},
	contactHeader: {
		fontSize: 8.5,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.magenta,
		marginBottom: 6,
		textTransform: 'uppercase',
	},
	contactName: {
		fontSize: 10.5,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.dark,
		marginBottom: 4,
	},
	contactRole: {
		fontSize: 7.5,
		color: COLORS.gray,
		marginBottom: 8,
	},
	contactBadge: {
		backgroundColor: COLORS.softBlueBg,
		borderRadius: 4,
		paddingVertical: 2,
		paddingHorizontal: 6,
		alignSelf: 'flex-start',
		marginTop: 4,
	},
	contactBadgeText: {
		fontSize: 7,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: '#005b8f',
	},
	contactButtonFilled: {
		backgroundColor: COLORS.magenta,
		borderRadius: 4,
		paddingVertical: 5,
		paddingHorizontal: 10,
		marginTop: 8,
		alignItems: 'center',
		justifyContent: 'center',
		textDecoration: 'none',
		display: 'flex',
		alignSelf: 'flex-start',
	},
	contactButtonFilledText: {
		fontSize: 7.5,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: COLORS.white,
		textAlign: 'center',
	},
	contactButtonOutline: {
		borderWidth: 1,
		borderColor: '#005b8f',
		backgroundColor: '#f6fbff',
		borderRadius: 4,
		paddingVertical: 5,
		paddingHorizontal: 10,
		marginTop: 8,
		alignItems: 'center',
		justifyContent: 'center',
		textDecoration: 'none',
		display: 'flex',
		alignSelf: 'flex-start',
	},
	contactButtonOutlineText: {
		fontSize: 7.5,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: '#005b8f',
		textAlign: 'center',
	},
	contactDetailRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginTop: 4,
		marginBottom: 4,
	},
	contactDetailText: {
		fontSize: 7.5,
		color: COLORS.gray,
		lineHeight: 1.3,
	},
	specialPriceHighlightBox: {
		backgroundColor: '#f2fcf7',
		borderColor: '#b2edd3',
		borderWidth: 1,
		borderRadius: 6,
		padding: 8,
		marginTop: 8,
	},
	specialPriceHeader: {
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		fontSize: 8.5,
		color: '#00a878',
		marginBottom: 4,
		textTransform: 'uppercase',
		letterSpacing: 0.3,
	},
	specialPriceRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		paddingVertical: 2,
	},
	specialPriceLabel: {
		fontSize: 8,
		fontFamily: 'TeleNeo',
		color: '#004d2e',
		flex: 1,
	},
	specialPriceValue: {
		fontSize: 8.5,
		fontFamily: 'TeleNeo',
		fontWeight: 'bold',
		color: '#00a878',
		textAlign: 'right',
	},
	dividerLine: {
		borderBottomWidth: 1.5,
		borderBottomColor: '#d3d3d3',
		marginTop: 15,
		marginBottom: 15,
	},
});
